# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/josephg/src/mime-to-jmap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/josephg/src/mime-to-jmap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/josephg/src/mime-to-jmap/CMakeFiles /Users/josephg/src/mime-to-jmap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/josephg/src/mime-to-jmap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mimer

# Build rule for target.
mimer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mimer
.PHONY : mimer

# fast build rule for target.
mimer/fast:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/build
.PHONY : mimer/fast

jansson/dump.o: jansson/dump.c.o

.PHONY : jansson/dump.o

# target to build an object file
jansson/dump.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/dump.c.o
.PHONY : jansson/dump.c.o

jansson/dump.i: jansson/dump.c.i

.PHONY : jansson/dump.i

# target to preprocess a source file
jansson/dump.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/dump.c.i
.PHONY : jansson/dump.c.i

jansson/dump.s: jansson/dump.c.s

.PHONY : jansson/dump.s

# target to generate assembly for a file
jansson/dump.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/dump.c.s
.PHONY : jansson/dump.c.s

jansson/error.o: jansson/error.c.o

.PHONY : jansson/error.o

# target to build an object file
jansson/error.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/error.c.o
.PHONY : jansson/error.c.o

jansson/error.i: jansson/error.c.i

.PHONY : jansson/error.i

# target to preprocess a source file
jansson/error.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/error.c.i
.PHONY : jansson/error.c.i

jansson/error.s: jansson/error.c.s

.PHONY : jansson/error.s

# target to generate assembly for a file
jansson/error.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/error.c.s
.PHONY : jansson/error.c.s

jansson/hashtable.o: jansson/hashtable.c.o

.PHONY : jansson/hashtable.o

# target to build an object file
jansson/hashtable.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable.c.o
.PHONY : jansson/hashtable.c.o

jansson/hashtable.i: jansson/hashtable.c.i

.PHONY : jansson/hashtable.i

# target to preprocess a source file
jansson/hashtable.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable.c.i
.PHONY : jansson/hashtable.c.i

jansson/hashtable.s: jansson/hashtable.c.s

.PHONY : jansson/hashtable.s

# target to generate assembly for a file
jansson/hashtable.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable.c.s
.PHONY : jansson/hashtable.c.s

jansson/hashtable_seed.o: jansson/hashtable_seed.c.o

.PHONY : jansson/hashtable_seed.o

# target to build an object file
jansson/hashtable_seed.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable_seed.c.o
.PHONY : jansson/hashtable_seed.c.o

jansson/hashtable_seed.i: jansson/hashtable_seed.c.i

.PHONY : jansson/hashtable_seed.i

# target to preprocess a source file
jansson/hashtable_seed.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable_seed.c.i
.PHONY : jansson/hashtable_seed.c.i

jansson/hashtable_seed.s: jansson/hashtable_seed.c.s

.PHONY : jansson/hashtable_seed.s

# target to generate assembly for a file
jansson/hashtable_seed.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/hashtable_seed.c.s
.PHONY : jansson/hashtable_seed.c.s

jansson/load.o: jansson/load.c.o

.PHONY : jansson/load.o

# target to build an object file
jansson/load.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/load.c.o
.PHONY : jansson/load.c.o

jansson/load.i: jansson/load.c.i

.PHONY : jansson/load.i

# target to preprocess a source file
jansson/load.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/load.c.i
.PHONY : jansson/load.c.i

jansson/load.s: jansson/load.c.s

.PHONY : jansson/load.s

# target to generate assembly for a file
jansson/load.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/load.c.s
.PHONY : jansson/load.c.s

jansson/memory.o: jansson/memory.c.o

.PHONY : jansson/memory.o

# target to build an object file
jansson/memory.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/memory.c.o
.PHONY : jansson/memory.c.o

jansson/memory.i: jansson/memory.c.i

.PHONY : jansson/memory.i

# target to preprocess a source file
jansson/memory.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/memory.c.i
.PHONY : jansson/memory.c.i

jansson/memory.s: jansson/memory.c.s

.PHONY : jansson/memory.s

# target to generate assembly for a file
jansson/memory.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/memory.c.s
.PHONY : jansson/memory.c.s

jansson/pack_unpack.o: jansson/pack_unpack.c.o

.PHONY : jansson/pack_unpack.o

# target to build an object file
jansson/pack_unpack.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/pack_unpack.c.o
.PHONY : jansson/pack_unpack.c.o

jansson/pack_unpack.i: jansson/pack_unpack.c.i

.PHONY : jansson/pack_unpack.i

# target to preprocess a source file
jansson/pack_unpack.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/pack_unpack.c.i
.PHONY : jansson/pack_unpack.c.i

jansson/pack_unpack.s: jansson/pack_unpack.c.s

.PHONY : jansson/pack_unpack.s

# target to generate assembly for a file
jansson/pack_unpack.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/pack_unpack.c.s
.PHONY : jansson/pack_unpack.c.s

jansson/strbuffer.o: jansson/strbuffer.c.o

.PHONY : jansson/strbuffer.o

# target to build an object file
jansson/strbuffer.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strbuffer.c.o
.PHONY : jansson/strbuffer.c.o

jansson/strbuffer.i: jansson/strbuffer.c.i

.PHONY : jansson/strbuffer.i

# target to preprocess a source file
jansson/strbuffer.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strbuffer.c.i
.PHONY : jansson/strbuffer.c.i

jansson/strbuffer.s: jansson/strbuffer.c.s

.PHONY : jansson/strbuffer.s

# target to generate assembly for a file
jansson/strbuffer.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strbuffer.c.s
.PHONY : jansson/strbuffer.c.s

jansson/strconv.o: jansson/strconv.c.o

.PHONY : jansson/strconv.o

# target to build an object file
jansson/strconv.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strconv.c.o
.PHONY : jansson/strconv.c.o

jansson/strconv.i: jansson/strconv.c.i

.PHONY : jansson/strconv.i

# target to preprocess a source file
jansson/strconv.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strconv.c.i
.PHONY : jansson/strconv.c.i

jansson/strconv.s: jansson/strconv.c.s

.PHONY : jansson/strconv.s

# target to generate assembly for a file
jansson/strconv.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/strconv.c.s
.PHONY : jansson/strconv.c.s

jansson/utf.o: jansson/utf.c.o

.PHONY : jansson/utf.o

# target to build an object file
jansson/utf.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/utf.c.o
.PHONY : jansson/utf.c.o

jansson/utf.i: jansson/utf.c.i

.PHONY : jansson/utf.i

# target to preprocess a source file
jansson/utf.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/utf.c.i
.PHONY : jansson/utf.c.i

jansson/utf.s: jansson/utf.c.s

.PHONY : jansson/utf.s

# target to generate assembly for a file
jansson/utf.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/utf.c.s
.PHONY : jansson/utf.c.s

jansson/value.o: jansson/value.c.o

.PHONY : jansson/value.o

# target to build an object file
jansson/value.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/value.c.o
.PHONY : jansson/value.c.o

jansson/value.i: jansson/value.c.i

.PHONY : jansson/value.i

# target to preprocess a source file
jansson/value.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/value.c.i
.PHONY : jansson/value.c.i

jansson/value.s: jansson/value.c.s

.PHONY : jansson/value.s

# target to generate assembly for a file
jansson/value.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/jansson/value.c.s
.PHONY : jansson/value.c.s

src/arrayu64.o: src/arrayu64.c.o

.PHONY : src/arrayu64.o

# target to build an object file
src/arrayu64.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/arrayu64.c.o
.PHONY : src/arrayu64.c.o

src/arrayu64.i: src/arrayu64.c.i

.PHONY : src/arrayu64.i

# target to preprocess a source file
src/arrayu64.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/arrayu64.c.i
.PHONY : src/arrayu64.c.i

src/arrayu64.s: src/arrayu64.c.s

.PHONY : src/arrayu64.s

# target to generate assembly for a file
src/arrayu64.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/arrayu64.c.s
.PHONY : src/arrayu64.c.s

src/charset.o: src/charset.c.o

.PHONY : src/charset.o

# target to build an object file
src/charset.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/charset.c.o
.PHONY : src/charset.c.o

src/charset.i: src/charset.c.i

.PHONY : src/charset.i

# target to preprocess a source file
src/charset.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/charset.c.i
.PHONY : src/charset.c.i

src/charset.s: src/charset.c.s

.PHONY : src/charset.s

# target to generate assembly for a file
src/charset.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/charset.c.s
.PHONY : src/charset.c.s

src/chartable.o: src/chartable.c.o

.PHONY : src/chartable.o

# target to build an object file
src/chartable.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/chartable.c.o
.PHONY : src/chartable.c.o

src/chartable.i: src/chartable.c.i

.PHONY : src/chartable.i

# target to preprocess a source file
src/chartable.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/chartable.c.i
.PHONY : src/chartable.c.i

src/chartable.s: src/chartable.c.s

.PHONY : src/chartable.s

# target to generate assembly for a file
src/chartable.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/chartable.c.s
.PHONY : src/chartable.c.s

src/gmtoff_gmtime.o: src/gmtoff_gmtime.c.o

.PHONY : src/gmtoff_gmtime.o

# target to build an object file
src/gmtoff_gmtime.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_gmtime.c.o
.PHONY : src/gmtoff_gmtime.c.o

src/gmtoff_gmtime.i: src/gmtoff_gmtime.c.i

.PHONY : src/gmtoff_gmtime.i

# target to preprocess a source file
src/gmtoff_gmtime.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_gmtime.c.i
.PHONY : src/gmtoff_gmtime.c.i

src/gmtoff_gmtime.s: src/gmtoff_gmtime.c.s

.PHONY : src/gmtoff_gmtime.s

# target to generate assembly for a file
src/gmtoff_gmtime.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_gmtime.c.s
.PHONY : src/gmtoff_gmtime.c.s

src/gmtoff_tm.o: src/gmtoff_tm.c.o

.PHONY : src/gmtoff_tm.o

# target to build an object file
src/gmtoff_tm.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_tm.c.o
.PHONY : src/gmtoff_tm.c.o

src/gmtoff_tm.i: src/gmtoff_tm.c.i

.PHONY : src/gmtoff_tm.i

# target to preprocess a source file
src/gmtoff_tm.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_tm.c.i
.PHONY : src/gmtoff_tm.c.i

src/gmtoff_tm.s: src/gmtoff_tm.c.s

.PHONY : src/gmtoff_tm.s

# target to generate assembly for a file
src/gmtoff_tm.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/gmtoff_tm.c.s
.PHONY : src/gmtoff_tm.c.s

src/hash.o: src/hash.c.o

.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i

.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s

.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/htmlchar.o: src/htmlchar.c.o

.PHONY : src/htmlchar.o

# target to build an object file
src/htmlchar.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/htmlchar.c.o
.PHONY : src/htmlchar.c.o

src/htmlchar.i: src/htmlchar.c.i

.PHONY : src/htmlchar.i

# target to preprocess a source file
src/htmlchar.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/htmlchar.c.i
.PHONY : src/htmlchar.c.i

src/htmlchar.s: src/htmlchar.c.s

.PHONY : src/htmlchar.s

# target to generate assembly for a file
src/htmlchar.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/htmlchar.c.s
.PHONY : src/htmlchar.c.s

src/imapparse.o: src/imapparse.c.o

.PHONY : src/imapparse.o

# target to build an object file
src/imapparse.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imapparse.c.o
.PHONY : src/imapparse.c.o

src/imapparse.i: src/imapparse.c.i

.PHONY : src/imapparse.i

# target to preprocess a source file
src/imapparse.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imapparse.c.i
.PHONY : src/imapparse.c.i

src/imapparse.s: src/imapparse.c.s

.PHONY : src/imapparse.s

# target to generate assembly for a file
src/imapparse.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imapparse.c.s
.PHONY : src/imapparse.c.s

src/imparse.o: src/imparse.c.o

.PHONY : src/imparse.o

# target to build an object file
src/imparse.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imparse.c.o
.PHONY : src/imparse.c.o

src/imparse.i: src/imparse.c.i

.PHONY : src/imparse.i

# target to preprocess a source file
src/imparse.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imparse.c.i
.PHONY : src/imparse.c.i

src/imparse.s: src/imparse.c.s

.PHONY : src/imparse.s

# target to generate assembly for a file
src/imparse.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/imparse.c.s
.PHONY : src/imparse.c.s

src/jmap_api.o: src/jmap_api.c.o

.PHONY : src/jmap_api.o

# target to build an object file
src/jmap_api.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_api.c.o
.PHONY : src/jmap_api.c.o

src/jmap_api.i: src/jmap_api.c.i

.PHONY : src/jmap_api.i

# target to preprocess a source file
src/jmap_api.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_api.c.i
.PHONY : src/jmap_api.c.i

src/jmap_api.s: src/jmap_api.c.s

.PHONY : src/jmap_api.s

# target to generate assembly for a file
src/jmap_api.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_api.c.s
.PHONY : src/jmap_api.c.s

src/jmap_mail.o: src/jmap_mail.c.o

.PHONY : src/jmap_mail.o

# target to build an object file
src/jmap_mail.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail.c.o
.PHONY : src/jmap_mail.c.o

src/jmap_mail.i: src/jmap_mail.c.i

.PHONY : src/jmap_mail.i

# target to preprocess a source file
src/jmap_mail.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail.c.i
.PHONY : src/jmap_mail.c.i

src/jmap_mail.s: src/jmap_mail.c.s

.PHONY : src/jmap_mail.s

# target to generate assembly for a file
src/jmap_mail.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail.c.s
.PHONY : src/jmap_mail.c.s

src/jmap_mail_query.o: src/jmap_mail_query.c.o

.PHONY : src/jmap_mail_query.o

# target to build an object file
src/jmap_mail_query.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail_query.c.o
.PHONY : src/jmap_mail_query.c.o

src/jmap_mail_query.i: src/jmap_mail_query.c.i

.PHONY : src/jmap_mail_query.i

# target to preprocess a source file
src/jmap_mail_query.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail_query.c.i
.PHONY : src/jmap_mail_query.c.i

src/jmap_mail_query.s: src/jmap_mail_query.c.s

.PHONY : src/jmap_mail_query.s

# target to generate assembly for a file
src/jmap_mail_query.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_mail_query.c.s
.PHONY : src/jmap_mail_query.c.s

src/jmap_util.o: src/jmap_util.c.o

.PHONY : src/jmap_util.o

# target to build an object file
src/jmap_util.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_util.c.o
.PHONY : src/jmap_util.c.o

src/jmap_util.i: src/jmap_util.c.i

.PHONY : src/jmap_util.i

# target to preprocess a source file
src/jmap_util.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_util.c.i
.PHONY : src/jmap_util.c.i

src/jmap_util.s: src/jmap_util.c.s

.PHONY : src/jmap_util.s

# target to generate assembly for a file
src/jmap_util.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/jmap_util.c.s
.PHONY : src/jmap_util.c.s

src/json_support.o: src/json_support.c.o

.PHONY : src/json_support.o

# target to build an object file
src/json_support.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/json_support.c.o
.PHONY : src/json_support.c.o

src/json_support.i: src/json_support.c.i

.PHONY : src/json_support.i

# target to preprocess a source file
src/json_support.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/json_support.c.i
.PHONY : src/json_support.c.i

src/json_support.s: src/json_support.c.s

.PHONY : src/json_support.s

# target to generate assembly for a file
src/json_support.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/json_support.c.s
.PHONY : src/json_support.c.s

src/mailbox.o: src/mailbox.c.o

.PHONY : src/mailbox.o

# target to build an object file
src/mailbox.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mailbox.c.o
.PHONY : src/mailbox.c.o

src/mailbox.i: src/mailbox.c.i

.PHONY : src/mailbox.i

# target to preprocess a source file
src/mailbox.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mailbox.c.i
.PHONY : src/mailbox.c.i

src/mailbox.s: src/mailbox.c.s

.PHONY : src/mailbox.s

# target to generate assembly for a file
src/mailbox.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mailbox.c.s
.PHONY : src/mailbox.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/main.c.s
.PHONY : src/main.c.s

src/message.o: src/message.c.o

.PHONY : src/message.o

# target to build an object file
src/message.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message.c.o
.PHONY : src/message.c.o

src/message.i: src/message.c.i

.PHONY : src/message.i

# target to preprocess a source file
src/message.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message.c.i
.PHONY : src/message.c.i

src/message.s: src/message.c.s

.PHONY : src/message.s

# target to generate assembly for a file
src/message.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message.c.s
.PHONY : src/message.c.s

src/message_guid.o: src/message_guid.c.o

.PHONY : src/message_guid.o

# target to build an object file
src/message_guid.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message_guid.c.o
.PHONY : src/message_guid.c.o

src/message_guid.i: src/message_guid.c.i

.PHONY : src/message_guid.i

# target to preprocess a source file
src/message_guid.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message_guid.c.i
.PHONY : src/message_guid.c.i

src/message_guid.s: src/message_guid.c.s

.PHONY : src/message_guid.s

# target to generate assembly for a file
src/message_guid.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/message_guid.c.s
.PHONY : src/message_guid.c.s

src/mkgmtime.o: src/mkgmtime.c.o

.PHONY : src/mkgmtime.o

# target to build an object file
src/mkgmtime.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mkgmtime.c.o
.PHONY : src/mkgmtime.c.o

src/mkgmtime.i: src/mkgmtime.c.i

.PHONY : src/mkgmtime.i

# target to preprocess a source file
src/mkgmtime.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mkgmtime.c.i
.PHONY : src/mkgmtime.c.i

src/mkgmtime.s: src/mkgmtime.c.s

.PHONY : src/mkgmtime.s

# target to generate assembly for a file
src/mkgmtime.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mkgmtime.c.s
.PHONY : src/mkgmtime.c.s

src/mpool.o: src/mpool.c.o

.PHONY : src/mpool.o

# target to build an object file
src/mpool.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mpool.c.o
.PHONY : src/mpool.c.o

src/mpool.i: src/mpool.c.i

.PHONY : src/mpool.i

# target to preprocess a source file
src/mpool.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mpool.c.i
.PHONY : src/mpool.c.i

src/mpool.s: src/mpool.c.s

.PHONY : src/mpool.s

# target to generate assembly for a file
src/mpool.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/mpool.c.s
.PHONY : src/mpool.c.s

src/msgrecord.o: src/msgrecord.c.o

.PHONY : src/msgrecord.o

# target to build an object file
src/msgrecord.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/msgrecord.c.o
.PHONY : src/msgrecord.c.o

src/msgrecord.i: src/msgrecord.c.i

.PHONY : src/msgrecord.i

# target to preprocess a source file
src/msgrecord.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/msgrecord.c.i
.PHONY : src/msgrecord.c.i

src/msgrecord.s: src/msgrecord.c.s

.PHONY : src/msgrecord.s

# target to generate assembly for a file
src/msgrecord.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/msgrecord.c.s
.PHONY : src/msgrecord.c.s

src/parseaddr.o: src/parseaddr.c.o

.PHONY : src/parseaddr.o

# target to build an object file
src/parseaddr.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/parseaddr.c.o
.PHONY : src/parseaddr.c.o

src/parseaddr.i: src/parseaddr.c.i

.PHONY : src/parseaddr.i

# target to preprocess a source file
src/parseaddr.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/parseaddr.c.i
.PHONY : src/parseaddr.c.i

src/parseaddr.s: src/parseaddr.c.s

.PHONY : src/parseaddr.s

# target to generate assembly for a file
src/parseaddr.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/parseaddr.c.s
.PHONY : src/parseaddr.c.s

src/prot.o: src/prot.c.o

.PHONY : src/prot.o

# target to build an object file
src/prot.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/prot.c.o
.PHONY : src/prot.c.o

src/prot.i: src/prot.c.i

.PHONY : src/prot.i

# target to preprocess a source file
src/prot.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/prot.c.i
.PHONY : src/prot.c.i

src/prot.s: src/prot.c.s

.PHONY : src/prot.s

# target to generate assembly for a file
src/prot.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/prot.c.s
.PHONY : src/prot.c.s

src/ptrarray.o: src/ptrarray.c.o

.PHONY : src/ptrarray.o

# target to build an object file
src/ptrarray.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/ptrarray.c.o
.PHONY : src/ptrarray.c.o

src/ptrarray.i: src/ptrarray.c.i

.PHONY : src/ptrarray.i

# target to preprocess a source file
src/ptrarray.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/ptrarray.c.i
.PHONY : src/ptrarray.c.i

src/ptrarray.s: src/ptrarray.c.s

.PHONY : src/ptrarray.s

# target to generate assembly for a file
src/ptrarray.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/ptrarray.c.s
.PHONY : src/ptrarray.c.s

src/rfc822_header.o: src/rfc822_header.c.o

.PHONY : src/rfc822_header.o

# target to build an object file
src/rfc822_header.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822_header.c.o
.PHONY : src/rfc822_header.c.o

src/rfc822_header.i: src/rfc822_header.c.i

.PHONY : src/rfc822_header.i

# target to preprocess a source file
src/rfc822_header.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822_header.c.i
.PHONY : src/rfc822_header.c.i

src/rfc822_header.s: src/rfc822_header.c.s

.PHONY : src/rfc822_header.s

# target to generate assembly for a file
src/rfc822_header.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822_header.c.s
.PHONY : src/rfc822_header.c.s

src/rfc822tok.o: src/rfc822tok.c.o

.PHONY : src/rfc822tok.o

# target to build an object file
src/rfc822tok.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822tok.c.o
.PHONY : src/rfc822tok.c.o

src/rfc822tok.i: src/rfc822tok.c.i

.PHONY : src/rfc822tok.i

# target to preprocess a source file
src/rfc822tok.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822tok.c.i
.PHONY : src/rfc822tok.c.i

src/rfc822tok.s: src/rfc822tok.c.s

.PHONY : src/rfc822tok.s

# target to generate assembly for a file
src/rfc822tok.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/rfc822tok.c.s
.PHONY : src/rfc822tok.c.s

src/sequence.o: src/sequence.c.o

.PHONY : src/sequence.o

# target to build an object file
src/sequence.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/sequence.c.o
.PHONY : src/sequence.c.o

src/sequence.i: src/sequence.c.i

.PHONY : src/sequence.i

# target to preprocess a source file
src/sequence.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/sequence.c.i
.PHONY : src/sequence.c.i

src/sequence.s: src/sequence.c.s

.PHONY : src/sequence.s

# target to generate assembly for a file
src/sequence.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/sequence.c.s
.PHONY : src/sequence.c.s

src/strarray.o: src/strarray.c.o

.PHONY : src/strarray.o

# target to build an object file
src/strarray.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strarray.c.o
.PHONY : src/strarray.c.o

src/strarray.i: src/strarray.c.i

.PHONY : src/strarray.i

# target to preprocess a source file
src/strarray.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strarray.c.i
.PHONY : src/strarray.c.i

src/strarray.s: src/strarray.c.s

.PHONY : src/strarray.s

# target to generate assembly for a file
src/strarray.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strarray.c.s
.PHONY : src/strarray.c.s

src/strhash.o: src/strhash.c.o

.PHONY : src/strhash.o

# target to build an object file
src/strhash.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strhash.c.o
.PHONY : src/strhash.c.o

src/strhash.i: src/strhash.c.i

.PHONY : src/strhash.i

# target to preprocess a source file
src/strhash.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strhash.c.i
.PHONY : src/strhash.c.i

src/strhash.s: src/strhash.c.s

.PHONY : src/strhash.s

# target to generate assembly for a file
src/strhash.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/strhash.c.s
.PHONY : src/strhash.c.s

src/stristr.o: src/stristr.c.o

.PHONY : src/stristr.o

# target to build an object file
src/stristr.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/stristr.c.o
.PHONY : src/stristr.c.o

src/stristr.i: src/stristr.c.i

.PHONY : src/stristr.i

# target to preprocess a source file
src/stristr.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/stristr.c.i
.PHONY : src/stristr.c.i

src/stristr.s: src/stristr.c.s

.PHONY : src/stristr.s

# target to generate assembly for a file
src/stristr.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/stristr.c.s
.PHONY : src/stristr.c.s

src/times.o: src/times.c.o

.PHONY : src/times.o

# target to build an object file
src/times.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/times.c.o
.PHONY : src/times.c.o

src/times.i: src/times.c.i

.PHONY : src/times.i

# target to preprocess a source file
src/times.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/times.c.i
.PHONY : src/times.c.i

src/times.s: src/times.c.s

.PHONY : src/times.s

# target to generate assembly for a file
src/times.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/times.c.s
.PHONY : src/times.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/util.c.s
.PHONY : src/util.c.s

src/xmalloc.o: src/xmalloc.c.o

.PHONY : src/xmalloc.o

# target to build an object file
src/xmalloc.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xmalloc.c.o
.PHONY : src/xmalloc.c.o

src/xmalloc.i: src/xmalloc.c.i

.PHONY : src/xmalloc.i

# target to preprocess a source file
src/xmalloc.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xmalloc.c.i
.PHONY : src/xmalloc.c.i

src/xmalloc.s: src/xmalloc.c.s

.PHONY : src/xmalloc.s

# target to generate assembly for a file
src/xmalloc.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xmalloc.c.s
.PHONY : src/xmalloc.c.s

src/xsha1.o: src/xsha1.c.o

.PHONY : src/xsha1.o

# target to build an object file
src/xsha1.c.o:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xsha1.c.o
.PHONY : src/xsha1.c.o

src/xsha1.i: src/xsha1.c.i

.PHONY : src/xsha1.i

# target to preprocess a source file
src/xsha1.c.i:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xsha1.c.i
.PHONY : src/xsha1.c.i

src/xsha1.s: src/xsha1.c.s

.PHONY : src/xsha1.s

# target to generate assembly for a file
src/xsha1.c.s:
	$(MAKE) -f CMakeFiles/mimer.dir/build.make CMakeFiles/mimer.dir/src/xsha1.c.s
.PHONY : src/xsha1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mimer"
	@echo "... jansson/dump.o"
	@echo "... jansson/dump.i"
	@echo "... jansson/dump.s"
	@echo "... jansson/error.o"
	@echo "... jansson/error.i"
	@echo "... jansson/error.s"
	@echo "... jansson/hashtable.o"
	@echo "... jansson/hashtable.i"
	@echo "... jansson/hashtable.s"
	@echo "... jansson/hashtable_seed.o"
	@echo "... jansson/hashtable_seed.i"
	@echo "... jansson/hashtable_seed.s"
	@echo "... jansson/load.o"
	@echo "... jansson/load.i"
	@echo "... jansson/load.s"
	@echo "... jansson/memory.o"
	@echo "... jansson/memory.i"
	@echo "... jansson/memory.s"
	@echo "... jansson/pack_unpack.o"
	@echo "... jansson/pack_unpack.i"
	@echo "... jansson/pack_unpack.s"
	@echo "... jansson/strbuffer.o"
	@echo "... jansson/strbuffer.i"
	@echo "... jansson/strbuffer.s"
	@echo "... jansson/strconv.o"
	@echo "... jansson/strconv.i"
	@echo "... jansson/strconv.s"
	@echo "... jansson/utf.o"
	@echo "... jansson/utf.i"
	@echo "... jansson/utf.s"
	@echo "... jansson/value.o"
	@echo "... jansson/value.i"
	@echo "... jansson/value.s"
	@echo "... src/arrayu64.o"
	@echo "... src/arrayu64.i"
	@echo "... src/arrayu64.s"
	@echo "... src/charset.o"
	@echo "... src/charset.i"
	@echo "... src/charset.s"
	@echo "... src/chartable.o"
	@echo "... src/chartable.i"
	@echo "... src/chartable.s"
	@echo "... src/gmtoff_gmtime.o"
	@echo "... src/gmtoff_gmtime.i"
	@echo "... src/gmtoff_gmtime.s"
	@echo "... src/gmtoff_tm.o"
	@echo "... src/gmtoff_tm.i"
	@echo "... src/gmtoff_tm.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/htmlchar.o"
	@echo "... src/htmlchar.i"
	@echo "... src/htmlchar.s"
	@echo "... src/imapparse.o"
	@echo "... src/imapparse.i"
	@echo "... src/imapparse.s"
	@echo "... src/imparse.o"
	@echo "... src/imparse.i"
	@echo "... src/imparse.s"
	@echo "... src/jmap_api.o"
	@echo "... src/jmap_api.i"
	@echo "... src/jmap_api.s"
	@echo "... src/jmap_mail.o"
	@echo "... src/jmap_mail.i"
	@echo "... src/jmap_mail.s"
	@echo "... src/jmap_mail_query.o"
	@echo "... src/jmap_mail_query.i"
	@echo "... src/jmap_mail_query.s"
	@echo "... src/jmap_util.o"
	@echo "... src/jmap_util.i"
	@echo "... src/jmap_util.s"
	@echo "... src/json_support.o"
	@echo "... src/json_support.i"
	@echo "... src/json_support.s"
	@echo "... src/mailbox.o"
	@echo "... src/mailbox.i"
	@echo "... src/mailbox.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/message.o"
	@echo "... src/message.i"
	@echo "... src/message.s"
	@echo "... src/message_guid.o"
	@echo "... src/message_guid.i"
	@echo "... src/message_guid.s"
	@echo "... src/mkgmtime.o"
	@echo "... src/mkgmtime.i"
	@echo "... src/mkgmtime.s"
	@echo "... src/mpool.o"
	@echo "... src/mpool.i"
	@echo "... src/mpool.s"
	@echo "... src/msgrecord.o"
	@echo "... src/msgrecord.i"
	@echo "... src/msgrecord.s"
	@echo "... src/parseaddr.o"
	@echo "... src/parseaddr.i"
	@echo "... src/parseaddr.s"
	@echo "... src/prot.o"
	@echo "... src/prot.i"
	@echo "... src/prot.s"
	@echo "... src/ptrarray.o"
	@echo "... src/ptrarray.i"
	@echo "... src/ptrarray.s"
	@echo "... src/rfc822_header.o"
	@echo "... src/rfc822_header.i"
	@echo "... src/rfc822_header.s"
	@echo "... src/rfc822tok.o"
	@echo "... src/rfc822tok.i"
	@echo "... src/rfc822tok.s"
	@echo "... src/sequence.o"
	@echo "... src/sequence.i"
	@echo "... src/sequence.s"
	@echo "... src/strarray.o"
	@echo "... src/strarray.i"
	@echo "... src/strarray.s"
	@echo "... src/strhash.o"
	@echo "... src/strhash.i"
	@echo "... src/strhash.s"
	@echo "... src/stristr.o"
	@echo "... src/stristr.i"
	@echo "... src/stristr.s"
	@echo "... src/times.o"
	@echo "... src/times.i"
	@echo "... src/times.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/xmalloc.o"
	@echo "... src/xmalloc.i"
	@echo "... src/xmalloc.s"
	@echo "... src/xsha1.o"
	@echo "... src/xsha1.i"
	@echo "... src/xsha1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

